### ISSUE TITLE
Directory structure

### ISSUE THREAD

**Issue by TokisanGames** [smix8/GodotAnimationRetargeting#10]
I'm building now to test and looking forward to trying out your module. Please consider moving your files for the module to /. This allows us to update the module directly within our godot tree. 

Thanks

**Comment by smix8** [comment]
Hey, I am lost in translation or have a muddy brain rightnow. What excact folder/directory structure would you prefer for the module? Do you want me to move the "animation_retargeting" content to the root folder?

**Comment by TokisanGames** [comment]
Yes. No animation_retargeting folder at all. Place SCsub, *.cpp, and all files directly in the root folder along side the license and readme.

People can then clone like this:
```
cd godot/modules
git clone https://github.com/smix8/GodotAnimationRetargeting.git animation_retargeting --branch godot_3.x
```

When they build, the module included. If they want to update it, they just `git pull` in the folder. Otherwise, we have to store it in a separate place, update it, copy and overwrite to the duplicate version in our godot tree.

**Comment by smix8** [comment]
Got you, makes sense. Will move the folders on next commit.

**Comment by smix8** [comment]
Fixed for Godot 3.x with commit 9ff772997782c4af18c8b867410f1f38aeeac708 and Godot 4.x with commit 85e33b26029335f98d0a8f63ca20f07860a7877d

**Comment by TokisanGames** [comment]
Thanks
