### ISSUE TITLE
Add option to retarget only new animations ("Retarget New Animations Only")

### ISSUE THREAD

**Issue by stryker313** [smix8/GodotAnimationRetargeting#30]
Currently the tool can retarget single animations or the whole animation player. There should be an option to retarget only the new animations of a skeleton, and load them into the animation player much like Retarget Animation Player.

ex.
AnimPlayer 1:
//Dodge
//Punch
//Kick

AnimPlayer 2:
//Dodge
//Punch
//Jump
//Swing
//Climb
There are situations where you would want to only import the new ones. ex. batch imports, avoiding overriding the functions in the animation tracks

You can retarget the anims one by one, but it can get tedious with a large import.

I imagine it could work like "Retarget animation player", except it only brings over the new animations, so maybe "Retarget New Animations Only".

**Comment by smix8** [comment]
So an additonal menu option to transfer and retarget only animation names found in the source animationplayer but not in the target animationplayer?

**Comment by stryker313** [comment]
Yeah.

**Comment by smix8** [comment]
@stryker313 
Any naming suggestions or are we good?
![retarget_mode_naming](https://user-images.githubusercontent.com/52464204/126826016-f3a97ae3-91a0-4bb1-97e3-3ed31ca68df8.PNG)

**Comment by smix8** [comment]
added with commit e6ecf341847ee56232ad83f49558cded4592c168
