### ISSUE TITLE
Add icon for AnimationRetargeting node

### ISSUE THREAD

**Issue by smix8** [smix8/GodotAnimationRetargeting#8]
Work on a GDScript version has shown that an icon is required by Godot cause the class register would complain if no valid icon is set when registering the addon.

I am not an icon designer so if anyone feels like it and wants to create an icon for this module/addon go for it.

**Comment by stryker313** [comment]
Here's a quick one I whipped up.
![retarget_icon](https://user-images.githubusercontent.com/83078010/116002588-75016500-a5c8-11eb-950f-1a25ed1a4927.png)

**Comment by smix8** [comment]
Thanks, I will use it for now to develop further.

I don't know for certain but .png files might create issues in the long run. Godot expects 16x16px svg icons that are colorcoded to the main purpose of the node and "red" is colorcode for spatial 3d nodes. I think it would be a better fit using the same color as AnimationPlayer and AnimationTree.
https://docs.godotengine.org/en/latest/development/editor/creating_icons.html

**Comment by stryker313** [comment]
Ok. Here is a redone one, 16x16, purple, but it is still png. Photoshop's svg exporter is glitchy, so hopefully at some point you can convert it and what not.
![Untitled-1](https://user-images.githubusercontent.com/83078010/116007165-5efd9f80-a5dc-11eb-84e6-c5d83b5d397d.png)

**Comment by smix8** [comment]
Thanks!

**Comment by smix8** [comment]
Added by commit 5959f4a4025e20f708d223e0e408eaa15186f113
